version: '3.3'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - proj
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: always
    networks:
      - proj
    volumes:
      - redis_data:/data

networks:
  proj:
    driver: bridge

volumes:
  redis_data:
    external: false
